version: '3.9'
services:
  hazelcast:
    hostname: hazelcast1
    container_name: hazelcast
    environment:
      HZ_NETWORK_JOIN_TCPIP_ENABLED: 'true'
    ports:
      - '5701:5701'
    image: 'hazelcast/hazelcast:5.4.0-SNAPSHOT'

# to start containers
# docker-compose up

# to remove the volumes
# docker-compose down -v

# For MC go to
# http://localhost:8080
# and enable dev mode